<?php

           // $sendbox_obj = new Sendbox_Shipping_API();
            $sever_obj = $_SERVER['REQUEST_URI'];
            $domain = $_SERVER['HTTP_HOST'];
            $self = $_SERVER['PHP_SELF'];
            $protocol = stripos($_SERVER['SERVER_PROTOCOL'],'https') === 0 ? 'https://' : 'http://';
            $params = "#carriers_temando-link";

            //build sendbox url
            $state = $protocol.$domain.$sever_obj.$params;
            $scopes= "profile";
            $static_url = $protocol.$domain.$self."/webhook/page/sendbox";
            $app_id =  $this->helper('Sendbox\Sendboxshipping\Helper\Data')->getConfig('carriers/sendboxshipping/appid');
            $sendbox_url = 'https://api.sendbox.co/oauth/access?app_id='.$app_id.'&scopes='.$scopes.'&redirect_url='.$static_url.'&state='.$state; 

            //start process to get auth token and refresh token 

               $server_res = ($_SERVER);
               $str = $server_res["REQUEST_URI"];
               parse_str($str, $output);
               //THIS IS WHERE IT STARTS O anyhow, lets go
              if(isset($output['code'])){
                $sendbox_code = $output['code'];
                $s_url = 'https://api.sendbox.co/oauth/access/access_token?';
                $client_secret =  $this->helper('Sendbox\Sendboxshipping\Helper\Data')->getConfig('carriers/sendboxshipping/clientsecret');
                $url_oauth = $s_url.'app_id='.$app_id.'&redirect_url='.$static_url.'&client_secret='.$client_secret.'&code='.$sendbox_code.'';
                //$oauth_res = $sendbox_obj->get_api_response_by_curl($url_oauth);


                $handle = curl_init();
                curl_setopt($handle, CURLOPT_URL, $url_oauth);
                curl_setopt($handle, CURLOPT_RETURNTRANSFER, true);
                $oauth_res = curl_exec($handle);
                curl_close($handle);
             
                $oauth_obj = json_decode($oauth_res);
                $oauth_token = ""; 
                $refresh_token = ""; 
                
                if(isset($oauth_obj->access_token)){
                    $oauth_token = $oauth_obj->access_token;
                }
                if(isset($oauth_obj->refresh_token)){
                    $refresh_token = $oauth_obj->refresh_token;
                }


                $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
                $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
                $connection = $resource->getConnection();
                $tableName = $resource->getTableName("sendbox"); //gives table name with prefix
    
                //Insert Data into table
                
                $sql = "INSERT INTO " .$tableName. " (auth_token, refresh_token) Values ('" .$oauth_token. "' ,'" .$refresh_token. "' )";
                //var_dump($sql);
                $connection->query($sql); 

               }

          

            
?>


<div class="pp-buttons-container">
    <p>
        <button>
        <a href="<?php echo($sendbox_url);?>" >
            <?php echo __('Connect to Sendbox') ?>
            </a>
        </button>
    </p>
</div>