<?php

class Sendbox_Shipping_API{
    //make a post to sendbox api using curl.
    public function post_on_api_by_curl($url, $data, $api_key)
    {
        $ch = curl_init($url);
        // Setup request to send json via POST.
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json', 'Authorization:' . $api_key));
        // Return response instead of printing.
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        // Send request.
        $result = curl_exec($ch);
        curl_close($ch);
        // Print response.
        return $result;
    }

     //make a get request using curl to sendbox

     public function get_api_response_by_curl($url)
     {
         $handle = curl_init();
         curl_setopt($handle, CURLOPT_URL, $url);
         curl_setopt($handle, CURLOPT_RETURNTRANSFER, true);
         $output = curl_exec($handle);
         curl_close($handle);
         return $output;
     }
     //make request to sendbox with header
 
     public function get_api_response_with_header($url, $request_headers){
         $ch = curl_init($url);
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
         curl_setopt($ch, CURLOPT_HTTPHEADER, $request_headers);
         $season_data = curl_exec($ch);
         if (curl_errno($ch)) {
             print "Error: " . curl_error($ch);
             exit();
         }
         // Show me the result
         curl_close($ch);
         return $season_data;
 
     }
 
 
     //all sendbox endpoints
     public function get_sendbox_api_url($url_type)
     {
         if ('delivery_quote' == $url_type) {
             $url = 'https://api.sendbox.ng/v1/merchant/shipments/delivery_quote';
         } elseif ('countries' == $url_type) {
             $url = 'https://api.sendbox.co/auth/countries?page_by={' . '"per_page"' . ':264}';
         }
         elseif('city' == $url_type){
             $url = 'https://api.sendbox.co/auth/cities?page_by=&filter_by={"state_code":"LOS"}';
         }
          elseif ('states' == $url_type) {
             $url = 'https://api.sendbox.co/auth/states?page_by={' . '"per_page"' . ':264}&filter_by={'.'"country_code"'.':"NG"'.'}';
         } elseif ('shipments' == $url_type) {
             $url = 'https://api.sendbox.ng/v1/merchant/shipments';
         } elseif ('item_type' == $url_type) {
             $url = 'https://api.sendbox.ng/v1/item_types';
         } elseif ('profile' == $url_type) {
             $url = 'https://api.sendbox.co/oauth/profile';
         }else {
             $url = '';
         }
         return $url;
     }
}
            $sendbox_obj = new Sendbox_Shipping_API();
            $sever_obj = $_SERVER['REQUEST_URI'];
            $domain = $_SERVER['HTTP_HOST'];
            $self = $_SERVER['PHP_SELF'];
            $protocol = stripos($_SERVER['SERVER_PROTOCOL'],'https') === 0 ? 'https://' : 'http://';
            $params = "#carriers_temando-link";

            //build sendbox url
            $state = $protocol.$domain.$sever_obj.$params;
            $scopes= "profile";
            $static_url = $protocol.$domain.$self."/webhook/page/sendbox";
            $app_id =  $this->helper('Sendbox\Sendboxshipping\Helper\Data')->getConfig('carriers/sendboxshipping/appid');
            $sendbox_url = 'https://api.sendbox.co/oauth/access?app_id='.$app_id.'&scopes='.$scopes.'&redirect_url='.$static_url.'&state='.$state; 

            //start process to get auth token and refresh token 

               $server_res = ($_SERVER);
               $str = $server_res["REQUEST_URI"];
               parse_str($str, $output);
               //THIS IS WHERE IT STARTS O anyhow, lets go
              if(isset($output['code'])){
                $sendbox_code = $output['code'];
                $s_url = 'https://api.sendbox.co/oauth/access/access_token?';
                $client_secret =  $this->helper('Sendbox\Sendboxshipping\Helper\Data')->getConfig('carriers/sendboxshipping/clientsecret');
                $url_oauth = $s_url.'app_id='.$app_id.'&redirect_url='.$static_url.'&client_secret='.$client_secret.'&code='.$sendbox_code.'';
                $oauth_res = $sendbox_obj->get_api_response_by_curl($url_oauth);
                $oauth_obj = json_decode($oauth_res);
                $oauth_token = ""; 
                $refresh_token = ""; 
                
                if(isset($oauth_obj->access_token)){
                    $oauth_token = $oauth_obj->access_token;
                }
                if(isset($oauth_obj->refresh_token)){
                    $refresh_token = $oauth_obj->refresh_token;
                }


                $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
                $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
                $connection = $resource->getConnection();
                $tableName = $resource->getTableName("sendbox"); //gives table name with prefix
    
                //Insert Data into table
                
                $sql = "INSERT INTO " .$tableName. " (auth_token, refresh_token) Values ('" .$oauth_token. "' ,'" .$refresh_token. "' )";
                //var_dump($sql);
                $connection->query($sql); 

               }

          

            
?>


<div class="pp-buttons-container">
    <p>
        <button>
        <a href="<?php echo($sendbox_url);?>" >
            <?php echo __('Connect to Sendbox') ?>
            </a>
        </button>
    </p>
</div>